package BlizzApi

type AutoGenerated struct {
	Links               Links                 `json:"_links"`
	CurrentLeaderboards []CurrentLeaderboards `json:"current_leaderboards"`
}
type Self struct {
	Href string `json:"href"`
}
type Links struct {
	Self Self `json:"self"`
}
type Key struct {
	Href string `json:"href"`
}
type Name struct {
	EnUS string `json:"en_US"`
	EsMX string `json:"es_MX"`
	PtBR string `json:"pt_BR"`
	DeDE string `json:"de_DE"`
	EnGB string `json:"en_GB"`
	EsES string `json:"es_ES"`
	FrFR string `json:"fr_FR"`
	ItIT string `json:"it_IT"`
	RuRU string `json:"ru_RU"`
	KoKR string `json:"ko_KR"`
	ZhTW string `json:"zh_TW"`
	ZhCN string `json:"zh_CN"`
}
type CurrentLeaderboards struct {
	Key  Key  `json:"key"`
	Name Name `json:"name"`
	ID   int  `json:"id"`
}
