package BlizzApi

type AutoGenerated struct {
	Links                Links             `json:"_links"`
	Map                  Map               `json:"map"`
	Period               int               `json:"period"`
	PeriodStartTimestamp int64             `json:"period_start_timestamp"`
	PeriodEndTimestamp   int64             `json:"period_end_timestamp"`
	ConnectedRealm       ConnectedRealm    `json:"connected_realm"`
	LeadingGroups        []LeadingGroups   `json:"leading_groups"`
	KeystoneAffixes      []KeystoneAffixes `json:"keystone_affixes"`
	MapChallengeModeID   int               `json:"map_challenge_mode_id"`
	Name                 Name              `json:"name"`
}
type Self struct {
	Href string `json:"href"`
}
type Links struct {
	Self Self `json:"self"`
}
type Name struct {
	EnUS string `json:"en_US"`
	EsMX string `json:"es_MX"`
	PtBR string `json:"pt_BR"`
	DeDE string `json:"de_DE"`
	EnGB string `json:"en_GB"`
	EsES string `json:"es_ES"`
	FrFR string `json:"fr_FR"`
	ItIT string `json:"it_IT"`
	RuRU string `json:"ru_RU"`
	KoKR string `json:"ko_KR"`
	ZhTW string `json:"zh_TW"`
	ZhCN string `json:"zh_CN"`
}
type Map struct {
	Name Name `json:"name"`
	ID   int  `json:"id"`
}
type ConnectedRealm struct {
	Href string `json:"href"`
}
type Key struct {
	Href string `json:"href"`
}
type Realm struct {
	Key  Key    `json:"key"`
	ID   int    `json:"id"`
	Slug string `json:"slug"`
}
type Profile struct {
	Name  string `json:"name"`
	ID    int    `json:"id"`
	Realm Realm  `json:"realm"`
}
type Faction struct {
	Type string `json:"type"`
}
type Specialization struct {
	Key Key `json:"key"`
	ID  int `json:"id"`
}
type Members struct {
	Profile        Profile        `json:"profile"`
	Faction        Faction        `json:"faction"`
	Specialization Specialization `json:"specialization"`
}
type Color struct {
	R int     `json:"r"`
	G int     `json:"g"`
	B int     `json:"b"`
	A float64 `json:"a"`
}
type MythicRating struct {
	Color  Color   `json:"color"`
	Rating float64 `json:"rating"`
}
type LeadingGroups struct {
	Ranking            int          `json:"ranking"`
	Duration           int          `json:"duration"`
	CompletedTimestamp int64        `json:"completed_timestamp"`
	KeystoneLevel      int          `json:"keystone_level"`
	Members            []Members    `json:"members"`
	MythicRating       MythicRating `json:"mythic_rating"`
}
type KeystoneAffix struct {
	Key  Key  `json:"key"`
	Name Name `json:"name"`
	ID   int  `json:"id"`
}
type KeystoneAffixes struct {
	KeystoneAffix KeystoneAffix `json:"keystone_affix"`
	StartingLevel int           `json:"starting_level"`
}
